### PR TITLE
Use SVG icon for theme switcher

### LINKED ISSUE #144: Inconsistent display of the theme switcher icon
The theme switcher icon relies on the system font which can vary a lot. I set `font-size: 140%` for mine (it was barely visible in Chrome on Linux) and here is what I got:

WindowsLinux FirefoxLinux Chrome
WindowsLinux FirefoxLinux Chrome

From left to right: Windows (both Firefox and Chrome), Linux (Firefox), Linux (Chrome). Not only does the color vary, the size isn't consistent either. So I now have it overly large on Windows, but at least it should be visible in any browser.

Maybe it's a good idea to use an SVG icon for this, at least optionally?

### PR DESCRIPTION
**Pull request by reuixiy**
Fixes #144

### CODE REVIEW

**Comment by reuixiy** [comment]
Yes, guess I can try it.

**Comment by reuixiy** [comment]
Done. Any other suggestions?

**Comment by reuixiy** [comment]
Cool! How did you do it!

**Comment by palant** [comment]
> Cool! How did you do it!

Manually :smile:. The original SVG uses lots of Bezier curves when it's really only four arcs. Sun icon is harder to "compress" but using arcs is still considerably more compact here.

The code looks good to me now, I didn't test it however.

**Comment by palant** [comment]
Theme switcher doesn't appear to be covered by the "center" header layout. Is that expected?

**Comment by reuixiy** [comment]
It should appears, although outside the menu

**Comment by palant** [comment]
Yes, that's what I see. So this is intentional and not a styling mistake?

**Comment by reuixiy** [comment]
Yes. Menu is optional, theme switcher and multilingual switcher are independent in layout "center".

**Pull request merged**
