### PR TITLE
feat: add support for giscus

### PR DESCRIPTION
**Pull request by kands-code**
Add support for giscus.

### CODE REVIEW

**Comment by kands-code** [comment]
Resolves #427.

**Comment by reuixiy** [comment]
Thanks! Will look into this ASAP!

**Comment by Borber** [comment]
I'm looking forward to it, please hurry 😋

**Comment by jalenzz** [comment]
waiting for this 😆

**Review by reuixiy — COMMENTED** [review]
Finally, I’m reviewing this PR. I’m going to add Giscus support from #397, since this PR contains other changes which makes it harder to merge. I will add @kands-code as one of co-authors in final merging commit and I’m going to close this PR.

See https://github.com/reuixiy/hugo-theme-meme/pull/397#pullrequestreview-1834655369 also.

Thanks for your contribution! Feel free to add another PR for other improvements!

**Pull request closed without merging**
