### PR TITLE
fix: Allow scripts and styles to load cross-origin, e.g. from Google Translate

### PR DESCRIPTION
**Pull request by palant**
I noticed that neither scripts nor styles of my websites were loading when somebody attempted to translate an article via Google Translate. That's due to `enableFingerprint = true` configuration option - it doesn't merely enable fingerprinting but also Subresource Integrity. Turns out, cross-origin requests with `integrity` attribute are blocked by default, otherwise these could be [misused to leak information](https://bugs.chromium.org/p/chromium/issues/detail?id=812667).

The solution consists of two parts:

1. Add `crossorigin="anonymous"` attribute to the requests in question (done here).
2. Add `Access-Control-Allow-Origin: *` header to JS/CSS requests - has to be done in server configuration.

The second part probably needs documenting. The other option would be to separate fingerprinting (useful by itself to avoid using outdated scripts/styles) and Subresource Integrity in the configuration.

### CODE REVIEW

**Comment by reuixiy** [comment]
Thanks!

> The other option would be to separate fingerprinting (useful by itself to avoid using outdated scripts/styles) and Subresource Integrity in the configuration.

Like this. It's a nice enhancement.

**Comment by palant** [comment]
> Like this. It's a nice enhancement.

Not something I can implement however. I'm stuck on Hugo 0.68.3 for a while, so the current theme version is unusable for me.

**Comment by palant** [comment]
I’m finally on the current MemE version again, so I can test this. The additional commit introduces a new `enableSRI` setting, so Subresource Integrity can now be turned on or off separately from fingerprinting. I only change the English-language config, you’ll need to adjust the Chinese one.

**Review by reuixiy — APPROVED** [review]
Thanks!﻿

**Comment by palant** [comment]
Merged, but the Chinese config change still needs to happen.

**Comment by reuixiy** [comment]
Yes! I'm about to push a commit... Guess I should do it firstly next time, before the approval on GitHub CLI.

Anyway, thanks again!

**Pull request merged**
