### PR TITLE
feat: Added search capability via lunr (fixes #163)

### LINKED ISSUE #163: Add search functionality?
Would it make sense to contribute the search functionality from palant.info? Hugo website recommends hugo-lunr for lunr.js integration which is an unnecessarily complicated way to do it and will fail in some scenarios. This functionality can be easily integrated into a theme, with lunr.js script as the only external dependency. The search itself will work on the client side then, without any server-side support (search index generated as a JSON file by Hugo itself).

### PR DESCRIPTION
**Pull request by palant**
I've been testing this extensively and it seems to be working in all configurations. There are quite a few improvements compared to what I have on my site right now. Notes:

* Only compatible with header layout "flex" so far. I have no idea where to put it with "center" and how to style it there.
* Some files have `search` as base name - these are generic and could theoretically work unchanged with any other search provider. Others are called `lunr-search` - that's the lunr-specific code.
* I corrected the ellipsis in the locale files, this is an unrelated change - meant to use it originally but ended up not doing it after all.
* Locales for Brazilian Portuguese and Chinese would need to be updated, also the Chinese config example. That's not something I can do.
* The rudimentary pluralization algorithm in `lunr-search.js` should do for the locales that currently exist. Cyrillic languages for example have more complicated pluralization rules, but I guess that we can think about that once we actually have the issue.
* Summary length is hardcoded at 70. That's the default value for `summaryLength` in Hugo configuration, reading out the actual value is sadly not possible.

### CODE REVIEW

**Comment by reuixiy** [comment]
Awesome! I will review them asap!

**Comment by reuixiy** [comment]
Okay, I just tested it and it works very well, except for the followings:

1. Cannot return to the "original" page unless refreshed
2. It seems that currently only supports English

**Comment by palant** [comment]
> Cannot return to the "original" page unless refreshed

That should be easy to fix - I'll add the previous page state to the history.

> It seems that currently only supports English

What do you mean? If I set `defaultContentLanguage` configuration option to `de` I get German text. Is multilingual mode the issue? How does `i18n` function work there?

**Comment by palant** [comment]
I tried out a multilanguage setup - multiple versions of the JS files are being generated there. So the German pages link to the German-language script which has German-language texts. What am I missing?

**Comment by reuixiy** [comment]
Multilingual mode works well. I mean the search functionality, seems not working for Chinese.

**Comment by reuixiy** [comment]
> Only compatible with header layout "flex" so far. I have no idea where to put it with "center" and how to style it there.

Maybe we can solve this by treating search link in menu as a toggle, instead of an input bar. So it will be a toggle, then click, then pop up a full screen overlay on the page, then input...

But this requires lots of code refactoring.

**Comment by palant** [comment]
> I mean the search functionality, seems not working for Chinese.

Oh, so lunr itself doesn't know what to do with Chinese? :disappointed:

**Comment by palant** [comment]
Found https://github.com/MihaiValentin/lunr-languages - that's the solution for additional lunr languages apparently. Will need to see how this can be incorporated. No Chinese however...

**Comment by reuixiy** [comment]
> Oh, so lunr itself doesn't know what to do with Chinese? :disappointed:

Yeah, it just returns empty result...

**Comment by palant** [comment]
There is a pull request for Chinese but for some reason it's just sitting there: https://github.com/MihaiValentin/lunr-languages/pull/53

**Comment by palant** [comment]
I added some code using History API - a new history entry is created when searching, so that the Back button brings you back to the original content. This is better than overlays, as it's the expected way for search to behave. There are some oddities here still, I'll look into this later.

**Comment by palant** [comment]
> **Edit**: Maybe the lack of progress is due to the nodejieba dependency. I don't think that this project has a good way of bundling dependencies right now.

Yes, that's definitely the issue here. nodejieba is written in C++ and relies on close to 5 MB in databases. I have no idea whether there is really no simpler way of splitting a Chinese sentence into words, but this definitely isn't something that can run off the web. So, sadly, no lunr for Chinese. :cry:

**Comment by palant** [comment]
Fixed the oddities with going back and forth - the missing part was respecting `history.state`, now you will get the search again even after reloading the page or after coming back from a different site.

What's missing now is support for non-English languages. I guess that I'll have to list the languages supported by `lunr-languages` right now and warn if an unsupported language is used.

**Comment by palant** [comment]
Note that URL doesn't change when you search - this is intentional. I could change it to something like "#search=test" and also respect this anchor when loading. But I doubt that allowing external links to the search is a good idea.

**Comment by palant** [comment]
There we go, non-English languages will work as well now. If the language isn't supported by the lunr-languages package a warning will be printed at build time.

So all done again.

**Comment by reuixiy** [comment]
Okay, so one last issue, I will be redirected to the search page if I search on the homepage and then click on the homepage.

**Comment by palant** [comment]
Ok, changing URL when searching it is. Looks like no more issues now.

**Comment by palant** [comment]
Noticed an issue on an actual tablet. In landscape mode they have enough space to display the drop-down menu. But when you click the search field the virtual keyboard pops up and occupies lots of vertical screen space - search field loses focus and the menu closes.

**Comment by reuixiy** [comment]
Reproduced. Might be a bug caused by the popped keyboard.

**Pull request merged**
