### PR TITLE
feat: add new shareOnMastodon and shareOnFediverse option

### PR DESCRIPTION
**Pull request by palant**
It has been a while since I touched the theme, so I might have missed something @reuixiy.

This adds a “Share on Mastodon” button. That’s somewhat less trivial than usual because a Mastodon instance needs to be selected, requiring an intermediate page. The page I created is heavily inspired by [Share₂Fedi](https://s2f.kytta.dev/) but doesn’t require server-side support. Also, parameters are passed via `location.hash` rather than the query string, meaning that they won’t be visible in server logs (privacy).

There is a request to `api.fediverse.observer` to populate the list of suggested instances. This request is happening at build time which a) might slow down the build process and b) might get outdated if the site is rarely updated. Nevertheless, I consider this solution better than a client-side request. Fediverse Observer doesn’t allow filtering the list other than by status, meaning that users would have to download 8 MB of data. With the filtering done by Hugo, it’s only 600 instances left (around 30 kB). Hugo can also be [configured to cache this request](https://gohugo.io/getting-started/configuration/#configure-file-caches) so that it won’t be repeated unnecessarily.

Passing a parameter to `head.html` partial via `.Scratch` is very ugly but this was the only solution I could see in the short term.

Metadata of the share page seems mostly fine, thanks to the index page being passed as context. If anything, a better page title would be an option.

### CODE REVIEW

**Comment by palant** [comment]
I now added `shareOnMastodonFetchInstances` option to explicitly enabled that request to download instances. By default, no request will happen and the list will simply stay empty. I added it to the English example configuration, you will need to add to Chinese configurations yourself.

**Comment by reuixiy** [comment]
I love fediverse! Can you provide an additional screencast of this feature to help me review?

**Comment by palant** [comment]
This is the icon:

Share on Mastodon icon

And this is the page that opens when it is clicked:

Share on Mastodon form

Here I clicked “Remember instance” before and it saved my Mastodon instance. Otherwise, it wouldn’t be checked by default.

I just realized that I don’t remember where I got this Mastodon icon from (it has been used on my site for years). I’ll check that.

**Comment by palant** [comment]
Oh, and here is what it looks like after clicking “Continue to Mastodon”:

Mastodon publish form with text pre-filled

**Comment by palant** [comment]
> I just realized that I don’t remember where I got this Mastodon icon from (it has been used on my site for years). I’ll check that.

It’s Font Awesome, just like all the other icons. So it’s all fine here.

**Comment by palant** [comment]
I am somewhat undecided as to where to go from here. My original intent was adding more share icons for other Fediverse apps like KBin or Lemmy in subsequent pull requests. However, there are simply too many if you look at the [projects supported by Share₂Fedi](https://github.com/kytta/share2fedi/blob/1a7d013fb4d1fdd945d9e6ca55da5cae07a50f3a/src/lib/project.ts#L36).

Now it is possible to have a universal share form. It would determine the kind of software running on the instance and create the appropriate link. It would make sense. Except: what should be the icon then?

There are icons for [Fediverse](https://github.com/FortAwesome/Font-Awesome/issues/16252) and [ActivityPub](https://github.com/FortAwesome/Font-Awesome/issues/19668). These aren’t exactly well-known however.

I think that the best course of action would be adding both Mastodon and Fediverse icons, doing exactly the same thing. If you agree, I’ll change this pull request accordingly.

**Comment by palant** [comment]
Ok, I’ve implemented this as a generic “Share on Fediverse” now. Notes:

* Both Mastodon and Fediverse icons are displayed but they do exactly the same thing. When hovered, the Fediverse icon is filled with a linear gradient which somewhat allows faking the colors of the original logo.
* A wide range of applications is supported (everything supported by Share₂Fedi plus KBin). However, it isn’t always possible to determine the application type correctly because `.well-known/nodeinfo` usually doesn’t have CORS headers set.
* That’s why the primary way of determining application type is via the pre-fetched instance list. I decided to include all instances with more than 10 active users, which resulted in a list with 2185 entries. Size of `fedishare.html` is now at 160 KiB which I consider acceptable.
* I realized that processing assets as HTML templates is a footgun: autoescaping is disabled, so this isn’t safe. However, a partial included from such a template has autoescaping enabled properly. So there is now a `components/fedishare.html` partial doing all the work, and the file under assets is minimal.
* With all applications, a combination of title, description and URL is being shared, usually mashed together into a single field. The only exception is KBin, it retrieves the metadata itself from the URL.

What it looks like. Share icons:

Share icons including Mastodon and Fediverse icons, the latter being active

The share form, this time without a saved instance:

Form titled Share on Mastodon, Fediverse instance field active

Next step on Mastodon:

A pre-filled Mastodon post form

Next step on KBin:

A pre-filled KBin post form

Next step on Hubzilla:

A pre-filled Hubzilla post form

Next step on Friendica:

A pre-filled Friendica post form

**Comment by palant** [comment]
All fixed:

* There is now a default list of instances, containing canonical instances for the projects that have them. It will be used if fetching instance list is disabled or fails.
* There are now separate `shareOnMastodon` and `shareOnFediverse` options. So it is possible to display either one icon and not only both of them.
* I renamed `shareOnFediverseFetchInstances` into `shareFetchFediverseInstances` – with two possible options to display icons, the relationship cannot be established via naming any more. Instead, I mentioned it in a comment.
* Added Diaspora and micro.blog as supported applications.

**Review by reuixiy — APPROVED** [review]

**Pull request merged**
