### PR TITLE
refactor: Improve code highlighting

### PR DESCRIPTION
**Pull request by palant**
This has two goals:

* Do not use JavaScript for code highlighting. Not only will it be problematic when JavaScript is disabled, it produces awkward visual effects when loading a page in dark mode (initial code highlighting is meant light theme).
* Make dark and light themes consistent. Switching between themes will currently produce wildly inconsistent highlighting - not merely colors change but also bold and italic text, also which parts of the code have different colors to stand out.

My initial approach was putting highlighting styles directly into the `light-theme`/`dark-theme` mixins. This unfortunately increases the CSS file size by 10kb because both of these mixins are used twice.

So instead I added the basic styles to `_highlight.css` and merely define the ten color variables in the mixins. This way the CSS file size even decreases slightly.

The downside is that changing/overriding styles is no longer merely a matter of running `hugo gen chromastyles`. On the other hand, people can now override specific variables fairly easily.

The other downside is that not all styles are usable in this way. I used the dracula style as a template, but simply taking color values from rainbow_dash for the light mode didn't work - this style uses color values that are very close to each other, relying heavily on bold text as distinctive factor. I decided to use manni style instead which is similar but has sufficiently distinctive colors.

Here is what light/dark mode highlighting used to look like in comparison:

Light mode code snippet 1
Dark mode code snippet 1
Light mode code snippet 2
Dark mode code snippet 2
Light mode code snippet 3
Dark mode code snippet 3

Here is what it looks like with this change (only light mode changed):

Light mode code snippet 1
Dark mode code snippet 1
Light mode code snippet 2
Dark mode code snippet 2
Light mode code snippet 3
Dark mode code snippet 3

### CODE REVIEW

**Comment by palant** [comment]
I added one more commit here which isn't really related, merely to avoid a merge conflict later. I noticed a bug introduced by #169 - the brightness reduction in dark mode will only work if the user explicitly selected the them (`data-theme` attribute present), not when it was chosen implicitly. So now that the last rule not related to the theme switcher was moved away from `assets/scss/components/_dark-mode.scss`, maybe rename it into `_theme-switcher.scss`?

**Comment by reuixiy** [comment]
Nice approach!

> Maybe rename it into `_theme-switcher.scss`?

Agreed. And we can delete [the related code](https://github.com/reuixiy/hugo-theme-meme/blob/ea09a86fe6b7df41ba58bd842f0bb8bd3eb8443d/layouts/partials/utils/content.html#L179-L186) in `partials/utils/content.html` now.

Also, I think we should add a "BREAKING CHANGE" note for this, since the way to customize the style of code highlighting has changed.

**Comment by palant** [comment]
All done.

**Comment by reuixiy** [comment]
Yep, except that we didn't update the annoying `resources` folder with example config.toml for themes.gohugo.io.

**Comment by palant** [comment]
Done.

**Comment by reuixiy** [comment]
Thanks!

**Pull request merged**
